//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.MvcWebUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzellikTip
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Açıklama { get; set; }
        public int KategoriID { get; set; }
    }
}
